### ISSUE TITLE
nz-card-tab 、modal中不显示

### ISSUE THREAD

**Issue by apphost** [cipchk/ngx-tinymce#1]
1、置于非默认nz-card-tab中，tab切换后不显示。
2、置于nz-modal中，第一次打开modal可以显示，第二次打开modal不显示。

**Comment by cipchk** [comment]
麻烦提供一个在线stackblitz重现示例。

**Comment by apphost** [comment]
在ng-alain中，app/routes/editor/tinymce/tinymce.component.html修改如下可重现问题：

```
<div class="content__title">
    <h1>Tinymce
        <small>Dependencies
            <a href="//github.com/cipchk/ngx-tinymce" target="_blank">ngx-tinymce</a>
        </small>
    </h1>
</div>
<nz-card nzTitle="Basic">
    <nz-card-tab [nzTabHeading]="'Editor 1'">
        <tinymce [(ngModel)]="html" [config]="config" loading="加载中……"></tinymce>
    </nz-card-tab>
    <nz-card-tab [nzTabHeading]="'Editor 2'">
        <tinymce [(ngModel)]="html" [config]="config_classic" loading="loading……"></tinymce>
    </nz-card-tab>

</nz-card>
<nz-card nzTitle="Classic">
    <tinymce [(ngModel)]="html" [config]="config_classic" loading="loading……"></tinymce>
</nz-card>

```

1、Editor 2中的实例显示不了。
2、在reuseTab栏中关闭该页，再重新打开，Editor 1 和 Editor 2中的实例均显示不了。

**Comment by cipchk** [comment]
这个问题有点复杂，其实原因不在 ngx-tinymce 而在于 nz-card 的机制引起的，tinymce 在加载过程中需要一个明确的容器，但又由于 nz-card 的 tab 标签实现原因，导致 editor2 已经实例过，但实际在实例过程中容器还无法被渲染在DOM树中，结果渲染失败。

当然 reuse 也是同理。

目前恐怕没办法使用 ngx-tinymce 解决这个问题，或许你可以在外部当 nz-card 标签变更回调时重新渲染一个 tinymce 编辑器，除此之外没有什么好的办法。
