### ISSUE TITLE
Fix package json again

### ISSUE THREAD

**Issue by cubidobusinesssolutions** [cipchk/ngx-tinymce#11]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Actual behavior
See #8, i.e. again create a separate package.json for published npm package with `peerDependencies` instead of `dependencies` in order to avoid the following compile warning
>WARNING in ./node_modules/ngx-tinymce/node_modules/@angular/core/fesm5/core.js
>4826:15-36 Critical dependency: the request of a dependency is an expression

>WARNING in ./node_modules/ngx-tinymce/node_modules/@angular/core/fesm5/core.js
>4838:15-102 Critical dependency: the request of a dependency is an expression

## Expected behavior
Compiles without warnings

## Minimal reproduction of the problem with instructions
> yarn add ngx-tinymce
> yarn

`package.json`
```json
{
  "name": "ngx-tinymce",
  "version": "2.0.1",
  "main": "./bundles/tinymce.umd.js",
  "module": "./esm5/tinymce.js",
  "es2015": "./esm2015/tinymce.js",
  "typings": "./tinymce.d.ts",
  "description": "Angular for tinymce",
  "license": "MIT",
  "author": "cipchk",
  "homepage": "https://cipchk.github.io/ngx-tinymce/",
  "bugs": {
    "url": "https://github.com/cipchk/ngx-tinymce/issues"
  },
  "scripts": {
    "analyze": "ng build --prod --build-optimizer --stats-json",
    "lint": "tslint -p tsconfig.json -c tslint.json 'lib/*/*.ts'",
    "test": "ng test --code-coverage",
    "site:build": "ng build --prod --build-optimizer",
    "site:gh": "ng build --prod --build-optimizer --base-href /ngx-tinymce/ && gh-pages -d ./dist",
    "build": "bash ./build.sh",
    "release:next": "bash ./build.sh && cd publish && npm publish --access public --tag next",
    "release": "bash ./build.sh && cd publish && npm publish --access public"
  },
  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    ...
  },
  "devDependencies": {
    ...
  }
}
```

**Comment by cipchk** [comment]
Sorry, my mistake, i ingored in last refactoring.
