### ISSUE TITLE
在ie下使用form-group时无法获取值并且值无法回填

### ISSUE THREAD

**Issue by zhangjinsong** [cipchk/ngx-tinymce#13]
![image](https://user-images.githubusercontent.com/12949599/48564753-fb161d80-e931-11e8-89c8-fa5f6047ed5c.png)
这是我的输入值
![image](https://user-images.githubusercontent.com/12949599/48564789-0bc69380-e932-11e8-9dc5-000bdff64412.png)
这是w我的代码
保存成功后值为空
![image](https://user-images.githubusercontent.com/12949599/48564880-387aab00-e932-11e8-8bdb-701c15f1724e.png)

**Comment by zhangjinsong** [comment]
并且无法使用formgroup进行验证，请问这个问题我改如何解决

**Comment by cipchk** [comment]
ngx-tinymce 并不会对 tinymce 有任何的改动，建议一方面能提供一下可重现的示例，或提供更多的可用于分析的信息，亦或至 tinymce 官网检索 是否有对应的问题。

**Comment by zhangjinsong** [comment]
不好意思这么久才回复，下面是我的代码演示，请在ie下打开就能重现我的问题。
https://angular-blhmxf.stackblitz.io/

**Comment by zhangjinsong** [comment]
https://stackblitz.com/edit/angular-blhmxf

**Comment by cipchk** [comment]
问题一：建议使用 `FormBuilder` 来构建 `FormGroup`。
问题二：麻烦提供相应的错误信息，虽然有重现，但不代表我们是一致的。

**Comment by zhangjinsong** [comment]
实在抱歉。我找到错误的原因了。
