### ISSUE TITLE
How to give placeholder 

### ISSUE THREAD

**Issue by nirupamab5** [cipchk/ngx-tinymce#14]
Place holder issue in import { NgxTinymceModule } from 'ngx-tinymce'; 
<tinymce [config]="config"></tinymce>

**Comment by cipchk** [comment]
```html
<tinymce #comp [config]="config">
```

```ts
@ViewChild('comp') comp: TinymceComponent;

// you can get tinymce instance
comp['instance'];
```

**Comment by nirupamab5** [comment]
with comp['instance'] how can we give placeholder for tinymce component?

**Comment by cipchk** [comment]
i just only tell you how to get the current tinymce instance, other pls refer to https://www.tiny.cloud/docs/

**Comment by nirupamab5** [comment]
I have gone through documentation tried it any many ways to give just placeholder in tinymce component nothing works out. thank u for the info :)

**Comment by cipchk** [comment]
i will add `placeholder` property, but need to cooperate with [tinymce-placeholder](https://github.com/mohan/tinymce-placeholder), good luck!!

**Comment by nirupamab5** [comment]
Thank you, let me know once you add the placeholder property.

**Comment by nirupamab5** [comment]
thank you, let me know once placeholder property is added.

**Comment by gsse7en** [comment]
I'm stuck bad with this issue, documentation gets me nowhere, [tinymce-placeholder](https://github.com/mohan/tinymce-placeholder) is abandoned, placeholder just don't show nomatter what
tried making custom placeholdert label but can't focus tinymce component or simulate click on it

**Comment by cipchk** [comment]
Pls refer to [placeholder](https://www.tiny.cloud/docs/configure/editor-appearance/#placeholder) property for TinyMCE 5.2 and later.
