### ISSUE TITLE
tinymce js文件加载失败 ?

### ISSUE THREAD

**Issue by marie-dk** [cipchk/ngx-tinymce#15]
I followed the instructions for installing and using ngx-tinymce, and it works like a charm :-)
But for some reason I get an error in the console:

```
Error: tinymce js文件加载失败
"    at TinymceComponent.push../node_modules/ngx-tinymce/fesm5/ngx-tinymce.js.TinymceComponent.init (http://localhost:4200/en/vendor.js:123781:19)
"    at TinymceComponent.push../node_modules/ngx-tinymce/fesm5/ngx-tinymce.js.TinymceComponent.initDelay (http://localhost:4200/en/vendor.js:123775:18)
"    at TinymceComponent.push../node_modules/ngx-tinymce/fesm5/ngx-tinymce.js.TinymceComponent.ngOnChanges (http://localhost:4200/en/vendor.js:123855:18)
"    at checkAndUpdateDirectiveInline (http://localhost:4200/en/vendor.js:59018:19)
"    at checkAndUpdateNodeInline (http://localhost:4200/en/vendor.js:60286:20)
"    at checkAndUpdateNode (http://localhost:4200/en/vendor.js:60248:16)
"    at debugCheckAndUpdateNode (http://localhost:4200/en/vendor.js:60882:38)
"    at debugCheckDirectivesFn (http://localhost:4200/en/vendor.js:60842:13)
"    at Object.updateDirectives (http://localhost:4200/en/main.js:11744:939)
"    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:4200/en/vendor.js:60834:21)

```
This error only appear when I set the variable containing the config for TinyMCE:

**In NgOnInit**
```
this.con.get('TINYMCE').then(res => {
      this.tinyConfig = JSON.parse(res);
});
```
**In html:**
```
<tinymce [(ngModel)]="messageBody" [config]="tinyConfig"></tinymce>
```

I don't read Chinese, but Google Translate tells me that it means something like "File not loaded".
An I can see that this message is thrown when window.tinymce does not exist.

- I checked in the network tab of debug console that tinymce.min.js is in fact fetched successfully.  
- I compared your Stackblitz demo with my code, and I don't see any significant differences.
- I ruled out that this could be an error in my config, by setting it to just {"menubar":false}. The error still appears.
- The error disappear if I do not set the config at all. 

As mentioned, TinyMCE is loaded, my config is working, and I can edit and format text. So it seems to work despite this error. 
So the question is, why this error appear... and how do I get rid of it?

Versions:

- Angular 7
- TinyMCE 4.9.1
- ngx-tinymce 2.1.1

**Comment by cipchk** [comment]
Just because of `this.tinyConfig = JSON.parse(res);` triggered`ngOnChanges` of ngx-tinymce before loading tinymce files.

You can trying to initialize tinymce after loading the configuration, like this:

```html
<tinymce *ngIf="tinyConfig" [(ngModel)]="messageBody" [config]="tinyConfig"></tinymce>
```

**Comment by marie-dk** [comment]
Thanks a lot, that fixed it ... Should have thought of that myself.

**Comment by cipchk** [comment]
i think ngx-tinymce should need self-healing for this issues, i will fix this in next version.

**Comment by marie-dk** [comment]
And thank you for creating this module. It makes it very easy to add self-hosted TinyMCE to a project. A lot of people seems to be struggling with that.
