### ISSUE TITLE
当值为“”空时显示undifined

### ISSUE THREAD

**Issue by wenpengpeng** [cipchk/ngx-tinymce#21]
ngx-tinymce使用的是7.0.0版本
当值为“”时就会出现如下图所示有个undifined的问题;
![image](https://user-images.githubusercontent.com/34331662/82403557-b4a6ff00-9a91-11ea-9103-f43168b674ee.png)
我把版本降为2.1.1版本就没有这个问题了，希望可以修复一下

**Comment by cipchk** [comment]
你可以试着给 `[ngModel]` 一个空字符串值。
