### ISSUE TITLE
ngx TinyMCE - Get plain text

### ISSUE THREAD

**Issue by CrackerakiUA** [cipchk/ngx-tinymce#37]
Can't find a way to get text from ngx-tinymce as we can do in vanile one. Is there a way to get editor? In component there is no such thing as `activeEditor` or `getContent`
```
const myText = tinyMCE.activeEditor.selection.getContent({ format: 'text' });
```

**Comment by cipchk** [comment]
You can get the current instance via `@ViewChild` , then you can access the tinymce `instance` property.
