### ISSUE TITLE
Cannot read property 'events' of null - (cipchk/ngx-editor v1.0.1)

### ISSUE THREAD

**Issue by ishantha-dhanushka** [cipchk/ngx-tinymce#5]
There is a issue in version 1.0.1 (Latest Version). I here attached a screen shots of web console. Also I have debugged the JS file. "**this.router**" is assigning a null value. And also version 1.0.0 is working correctly.

![1](https://user-images.githubusercontent.com/7909563/36090264-b7a1e1b6-1005-11e8-8829-f88c779e1fd7.PNG)
![2](https://user-images.githubusercontent.com/7909563/36090265-b7e6f436-1005-11e8-967f-17ebbdc23b80.PNG)

**Comment by cipchk** [comment]
You can import the `RouterModule` in to you root module.

I will next version fix this.

**Comment by ishantha-dhanushka** [comment]
I tried it using **RouterModule** in several times. But not successes.

**Comment by cipchk** [comment]
This is the minimum runnable version in [stackblitz](https://stackblitz.com/edit/ngx-tinymce?file=app%2Fapp.module.ts)
